name: dependency-review

on:
  - pull_request_target

jobs:
  shared:
    uses: amezin/js-actions-common/.github/workflows/shared-dependency-review.yml@872f5f6c0fb6afcc1bf57a70e61192d848ebb8ad # v5.1.2
    permissions:
      contents: read
      pull-requests: write
